#pragma once

#include <Windows.h>

#define _STREAM_COLOR(color) \
	[]() \
	{ \
		SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color); \
		return ""; \
	}() \

#define _F_RESET _STREAM_COLOR(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)

#define _F_RED(x) _STREAM_COLOR(FOREGROUND_RED | FOREGROUND_INTENSITY) << x << _F_RESET
#define _F_GREEN(x) _STREAM_COLOR(FOREGROUND_GREEN | FOREGROUND_INTENSITY) << x << _F_RESET
#define _F_BLUE(x) _STREAM_COLOR(FOREGROUND_BLUE | FOREGROUND_INTENSITY) << x << _F_RESET
#define _F_WHITE(x) _STREAM_COLOR(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) << x << _F_RESET
